name: os_specification
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none


environment:
  sdk: '>=2.16.0 <3.0.0'


dependencies:
  win_api:
    git:
      url: ssh://git@gitlab.upstorage.net:2289/a.som/win_api_module_cpp.git

dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.1
